Basic interactivity support. Hopefully I'll refactor this soon.

diff --git a/anypaste b/anypaste
--- a/anypaste
+++ b/anypaste
@@ -10,6 +10,8 @@ function check_size {
     [[ $(wc -c < "$1") -lt $2 ]] || (echo "WARNING: File is of compatible type for plugin $3, but is above size limit of $2 bytes" && false)
 }
 
+# PLUGINS
+
 function anypaste-sprunge {
     if [[ $1 == "upload" ]]
     then
@@ -68,6 +70,7 @@ function anypaste-instaudio {
 function anypaste-gfycat {
     case $1 in
         check_eligibility)
+            return 1
             ;;
     esac
 }
@@ -77,7 +80,17 @@ function anypaste-gfycat {
 ## BEGIN CORE ###
 #################
 
-# PARSE COMMAND LINE OPTIONS, DISPLAY HELP
+# INTERACTIVITY FUNCTIONS
+
+# Y is always default. Word your questions better. Be positive!
+# args: message
+function ap_i_yn {
+    echo -n "$1 [Y/n] "
+    read ap_attempt
+    [[ "$ap_attempt" != 'n' && "$ap_attempt" != 'N' ]]
+}
+
+# HELP
 
 ap_help='Usage: anypaste [-i] [-p plugin] [-c config_file_path] [file]
 Upload `file` to an automatically selected hosting site.
@@ -101,6 +114,8 @@ then
     echo "$ap_help"
     exit
 fi
+
+# PARSE OPTIONS
 
 ap_i='false'
 ap_f='false'
@@ -148,9 +163,11 @@ then
     cat > "$ap_cfg" <<< "ap_plugins=( 'anypaste-vgyme' 'anypaste-instaudio' 'anypaste-gfycat' 'anypaste-sprunge' )"
 fi
 
-# LOAD CONFIGURATION
+# LOAD AND CHECK CONFIGURATION
 
 source "$ap_cfg"
+
+[[ ${#ap_plugins[@]} -eq 0 ]] && echo 'No plugins listed in config!' && exit 1
 
 # GET FILE DATA
 
@@ -199,31 +216,74 @@ function upload_plugin {
 
 # LOOP THROUGH PLUGINS
 
-compatible_plugins=()
-for cur_plugin in "${ap_plugins[@]}"
-do
-    # CHECK PLUGIN ELIGIBILITY
-
-    if $ap_f || $cur_plugin check_eligibility "$ap_path" "$ap_file_ib"
-    then
-        $ap_f || check_config $cur_plugin || continue
-        compatible_plugins+=("$cur_plugin")
-        $ap_i && continue
-        # PERFORM UPLOAD
-        if upload_plugin $cur_plugin "$ap_path" "$ap_file_ib"
-        then
-            exit
-        else
-            echo 'Trying next plugin...'
-        fi
-    fi
-done
-
-if $ap_i
+if ! $ap_i || ap_i_yn 'Would you like to automatically find compatible plugins?'
 then
-    echo "The following compatible plugins were found: ${compatible_plugins[@]}"
-    echo 'Enter the full or partial name of them, then hit enter to search...'
+    compatible_plugins=()
+    for cur_plugin in "${ap_plugins[@]}"
+    do
+        # CHECK PLUGIN ELIGIBILITY
+
+        if $ap_f || $cur_plugin check_eligibility "$ap_path" "$ap_file_ib"
+        then
+            $ap_f || check_config $cur_plugin || continue
+            compatible_plugins+=("$cur_plugin")
+            $ap_i && continue
+            # PERFORM UPLOAD
+            if upload_plugin $cur_plugin "$ap_path" "$ap_file_ib"
+            then
+                exit
+            else
+                echo 'Trying next plugin...'
+            fi
+        fi
+    done
 else
-    echo ''
-    echo 'ERROR: No compatible plugins found. '
+    # Copying arrays is fun!
+    compatible_plugins=("${ap_plugins[@]}")
+fi
+
+if $ap_i && [[ ! ${#compatible_plugins[@]} -eq 0 ]]
+then
+    if [[ ${#compatible_plugins[@]} -eq 1 ]] 
+    then
+        echo "Only one compatible plugin was found: $compatible_plugins"
+        # we could have not put any exit stuff in this command, and put `exit $?` on the next line
+        # would that have been better? We may never know.
+        ap_i_yn 'Use it?' && upload_plugin $compatible_plugins "$ap_path" "$ap_file_ib" && exit || exit 1
+    fi
+    echo "The following plugins were found: ${compatible_plugins[@]}"
+    # keep asking for search terms until we find something
+    while true
+    do
+        echo ''
+        echo 'Enter the full or partial name of a plugin, then hit enter'
+        read ap_search_term
+        ap_matched_plugins=()
+        failed='false'
+        for cur_plugin in "${ap_plugins[@]}"
+        do
+            if [[ "$cur_plugin" =~ "$ap_search_term" ]]
+            then
+                ap_matched_plugins+=("$cur_plugin")
+            fi
+        done
+        if [[ ${#ap_matched_plugins[@]} -eq 0 ]]
+        then
+            echo 'No plugins containing your search term were found.'
+            continue
+        fi
+        if [[ ${#ap_matched_plugins[@]} -gt 1 ]]
+        then
+            echo "Multiple matching plugins: ${ap_matched_plugins[@]}"
+            echo 'Please refine your search.'
+            continue
+        fi
+        if ap_i_yn "Use plugin $ap_matched_plugins?"
+        then
+            upload_plugin $ap_matched_plugins "$ap_path" "$ap_file_ib" && exit
+        fi
+    done
+else
+    echo 'ERROR: No compatible plugins found.'
+    exit 1
 fi
