gofile and pixhost

diff --git a/anypaste b/anypaste
--- a/anypaste
+++ b/anypaste
@@ -25,11 +25,26 @@ function check_size {
 }
 
 function curl_form_upload {
-	curl -#fF "$1=@\"$ap_path\";type=$ap_mime" -A "$ap_ua" "$2" || { echo "${ap_ERROR}ERROR: Upload request did not return HTTP 200!${ap_RESET}" >&2 && return 1; }
+	local main_field
+	main_field=$1
+	shift
+	curl -#fF "$main_field=@\"$ap_path\";type=$ap_mime" -A "$ap_ua" "$@" || { echo "${ap_ERROR}ERROR: Upload request did not return HTTP 200!${ap_RESET}" >&2 && return 1; }
 }
 
 function curl_file_upload {
-	curl "-X$1" -#fT "$2" -A "$ap_ua" "$3" || { echo "${ap_ERROR}ERROR: Upload request did not return HTTP 200!${ap_RESET}" >&2 && return 1; }
+	# curl supports globby stuff in -T, so we must escape.
+	local t_arg
+	t_arg=$2
+	# I've officially broken emacs indentation
+	t_arg=${t_arg//[/\\[}
+	t_arg=${t_arg//]/\\]}
+	t_arg=${t_arg//{/\\{}
+	t_arg=${t_arg//\}/\\\}} # honestly no idea how bash parses this right
+	curl "-X$1" -#fT "$t_arg" -A "$ap_ua" "$3" || { echo "${ap_ERROR}ERROR: Upload request did not return HTTP 200!${ap_RESET}" >&2 && return 1; }
+}
+
+function curl_get {
+	curl -fsA "$ap_ua" "$1" || { echo "${ap_ERROR}ERROR: GET request did not return HTTP 200!${ap_RESET}" >&2 && return 1; }
 }
 
 # string json, string key -> string value
@@ -233,6 +248,71 @@ function keepsh {
 		echo 'direct'
 		echo 'deletable'
 		;;
+	esac
+}
+
+function gofile {
+	case $1 in
+	check_eligibility)
+		# unlimited file size, whatcha think of that?
+		;;
+	upload)
+		gofile_server_json=$(curl_get https://apiv2.gofile.io/getServer) || return 1
+		gofile_server=$(json_parse "$gofile_server_json" server)
+		gofile_upload_json=$(curl_form_upload file "https://${gofile_server}.gofile.io/uploadFile")
+		gofile_code=$(json_parse "$gofile_upload_json" code)
+		gofile_admin_code=$(json_parse "$gofile_upload_json" adminCode)
+		gofile_info_json=$(curl_get "https://apiv2.gofile.io/getUpload?c=$gofile_code")
+		gofile_direct=$(json_parse "$gofile_info_json" link)
+		echo 'Reminder: Gofile uploads are deleted after 10 days of inactivity.' >&2
+		echo >&2
+		echo "Link: https://gofile.io/d/$gofile_code"
+		echo "Direct: $gofile_direct"
+		echo "Edit: https://gofile.io/d/$gofile_code/edit"
+		echo "Admin Code: $gofile_admin_code"
+		echo
+		;;
+	get_info)
+		echo '[name]'
+		echo 'Gofile'
+		echo '[description]'
+		echo 'Generic file host with official API and /unlimited/ upload size. Donate to them!'
+		echo '[tags]'
+		echo 'private'
+		echo 'direct'
+		echo 'deletable'
+	esac
+}
+
+function pixhost {
+	case $1 in
+	check_eligibility)
+		[[ $ap_mime == image/@(png|gif|jpeg) ]] && check_size 10000000
+		;;
+	upload)
+		pixhost_json=$(curl_form_upload img https://api.pixhost.to/images -F content_type=0 -F max_th_size=500) || return 1
+		pixhost_link_slashed=$(json_parse "$pixhost_json" show_url)
+		pixhost_thumbnail_slashed=$(json_parse "$pixhost_json" th_url)
+		# they escape their slashes, monsters!
+		pixhost_link=${pixhost_link_slashed//\\/}
+		pixhost_thumbnail=${pixhost_thumbnail_slashed//\\/}
+		# it's possible to get the actual direct image URL instead of the thumbnail, but they
+		# clearly don't want hotlinking so I'll respect that.
+		echo ''
+		echo >&2
+		echo "Link: $pixhost_link"
+		echo "Direct: $pixhost_thumbnail"
+		echo
+		;;
+	get_info)
+		echo '[name]'
+		echo 'Pixhost'
+		echo '[description]'
+		echo 'Simple image host with official API. Direct links are scaled-down thumbnails.'
+		echo '[tags]'
+		echo 'private'
+		echo 'permanent'
+		echo 'direct' # idk if it really counts
 	esac
 }
 
@@ -1128,11 +1208,11 @@ function ap_create_config {
 # You'll need to uncomment (remove # at beginning of line) first
 # ap_plugins=(
 # 'sendvid' 'streamable' 'gfycat' # Videos/Gifs
-# 'tinyimg' 'imgur' # Images
+# 'tinyimg' 'imgur' 'pixhost' # Images
 # 'clyp' # Audio
 # 'hastebin' 'ixio' # Text
 # 'docdroid' # Documents
-# 'dmca_gripe' 'keepsh' 'transfersh' 'filemail' 'fileio' # Generic
+# 'dmca_gripe' 'gofile' 'keepsh' 'transfersh' 'filemail' 'fileio' # Generic
 # )
 
 # Make sure to use export `boop=whatever` for plugin settings, not just `boop=whatever`
@@ -1325,7 +1405,7 @@ function ap_main_inner {
 	ap_help='false'
 	ap_version='false'
 	ap_plugins=(
-		'sendvid' 'streamable' 'gfycat' 'tinyimg' 'imgur' 'clyp' 'hastebin' 'ixio' 'docdroid' 'dmca_gripe' 'keepsh' 'transfersh' 'filemail' 'fileio'
+		'sendvid' 'streamable' 'gfycat' 'tinyimg' 'imgur' 'pixhost' 'clyp' 'hastebin' 'ixio' 'docdroid' 'dmca_gripe' 'gofile' 'keepsh' 'transfersh' 'filemail' 'fileio'
 	)
 	ap_hooks=()
 	ap_hook_policy='lazy'
