First shot at filemail.
Also, fix a dumb bug with temporary files related to glob expansion (they were not being deleted on exit; hard to fit into our test infrastructure)

diff --git a/anypaste b/anypaste
--- a/anypaste
+++ b/anypaste
@@ -462,6 +462,64 @@ function docdroid {
 	esac
 }
 
+function filemail {
+	case $1 in
+	check_eligibility)
+		# 50GB??? I'll believe it when I see it...
+		check_size 50000000000
+		;;
+	upload)
+		local id key transfer_global_url transfer_base_url transfer_local_url transfer_host init chunk_size chunk_count complete link direct
+		set -x
+		chunk_size=5242880
+		chunk_count=$(( ap_size / chunk_size ))
+		(( ap_size % chunk_size != 0)) && (( chunk_count++ ))
+		init=$(curl -sf --data 'sourcedetails=plupload(html5)+%40+https%3A%2F%2Fwww.filemail.com%2F&days=7&confirmation=true' 'https://www.filemail.com/api/transfer/initialize')
+		if [[ $? -eq 22 ]]
+		then
+			echo 'Filemail initialization failed!' >&2
+			echo 'More likely than not, you exceeded your daily limit of two uploads per IP.' >&2
+			return 1
+		fi
+		id=$(json_parse "$init" 'transferid')
+		key=$(json_parse "$init" 'transferkey')
+		transfer_base_url=$(json_parse "$init" 'transferurl')
+		transfer_host=${transfer_base_url%/*}
+		# Other required fields are per-chunk and set in chunk loop
+		transfer_global_url="$transfer_base_url?transferid=$id&transferkey=$key&runtime=html5&chunksize=$chunk_size&thefilename=$ap_human_name&totalsize=$ap_size&chunks=$chunk_count&retry=0"
+		chunk_tmp_file=$(ap_mktemp)
+		echo >&2
+		for chunk_c in $(seq 0 $(( chunk_count - 1 )))
+		do
+			echo -ne "\rUploading chunk $(( chunk_c + 1)) of $chunk_count." >&2
+			tail -c "+$(( chunk_size * chunk_c ))" < "$ap_path" | head -c "$chunk_size" > "$chunk_tmp_file"
+			transfer_local_url="$transfer_global_url&chunk=$chunk_c"
+			curl -sfXPOST --data-binary "@$chunk_tmp_file" -H 'Content-Type: application/octet-stream' "$transfer_local_url" || return 1
+			rm -f "$chunk_c_file"
+		done
+		echo >&2
+		echo 'Finishing upload.' >&2
+		complete=$(curl -sfXPOST --data "transferid=$id&transferkey=$key&failed=false" 'https://www.filemail.com/api/transfer/complete')
+		link=$(json_parse "$complete" 'downloadurl')
+		# file_key includes filekey= at beginning
+		file_key=$(curl -sfL "$link" | grep -oE 'filekey=[a-zA-Z0-9_-]*')
+		direct="$transfer_host/api/file/get?$file_key"
+		echo >&2
+		echo "Link: $link"
+		echo "Direct: $direct"
+		echo
+		;;
+	get_info)
+		echo '[name]'
+		echo 'Filemail'
+		echo '[description]'
+		echo 'A generic file host supporting up to 50GB files (!!). Files are deleted after a week, though, and there is a weird chunked upload system.'
+		echo '[tags]'
+		echo 'private'
+		echo 'direct'
+	esac
+}
+
 function dmca_gripe {
 	case $1 in
 	check_eligibility)
@@ -1040,7 +1098,7 @@ function ap_create_config {
 # 'clyp' # Audio
 # 'hastebin' 'ixio' # Text
 # 'docdroid' # Documents
-# 'dmca_gripe' 'transfersh' 'fileio' # Generic
+# 'dmca_gripe' 'transfersh' 'filemail' 'fileio' # Generic
 # )
 
 # Make sure to use export `boop=whatever` for plugin settings, not just `boop=whatever`
@@ -1233,7 +1291,7 @@ function ap_main_inner {
 	ap_help='false'
 	ap_version='false'
 	ap_plugins=(
-		'sendvid' 'streamable' 'gfycat' 'tinyimg' 'imgur' 'vgyme' 'clyp' 'hastebin' 'ixio' 'docdroid' 'dmca_gripe' 'transfersh' 'fileio'
+		'sendvid' 'streamable' 'gfycat' 'tinyimg' 'imgur' 'vgyme' 'clyp' 'hastebin' 'ixio' 'docdroid' 'dmca_gripe' 'transfersh' 'filemail' 'fileio'
 	)
 	ap_hooks=()
 	ap_hook_policy='lazy'
@@ -1300,7 +1358,7 @@ function ap_main {
 	local exit_code
 	ap_main_inner "$@"
 	exit_code="$?"
-	rm -f "$ap_tmpdir/anypaste.*"
+	# rm -f "$ap_tmpdir"/anypaste.*
 	return "$exit_code"
 }
 
